### ISSUE TITLE
뷰 구현 패턴에 관한 질문

### ISSUE THREAD

**Issue by swafkorea** [grotesq/codelab-flutter-1st#2]
예전에 React Native 강좌도 수강했던 개발자입니다.
같은 강사님이 서로 다른 프레임워크를 비교하면서 강의를 해주실거 같아서 신청했고 잘 듣고 있습니다.

지난번 강의를 듣고 RN과 대비되면서 느꼈던 점은 뷰를 구성할때 마크업 태그를 사용하지 않다보니
로직과 뷰가  상대적으로 강하게 묶여 있다는 느낌입니다.

그것이 플러터의 기본 컨셉이고 실무에서도 그렇게 사용되는지, 아니면 로직(또는 모델, 컨트롤러)과 뷰가 분리되는 패턴이 있는건지 궁금합니다.

**Comment by unk** [comment]
플러터의 기본 컨셉입니다 :)
그렇다고 거대한 트리가 형성되도록 하지는 않고, 위젯 단위로 잘 정리를 해가면서 씁니다.

**Comment by swafkorea** [comment]
그렇군요. 감사합니다.
angular 나 vue 처럼 구성하는데 익숙하다보니 생소했습니다.
자주 쓰면서 익숙해지고 나름의 패턴도 찾을 수 있길 바래봅니다.
